image: python:3.9

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest flake8

test:
  stage: test
  script:
    - flake8 src/ tests/  # Проверка кода на стиль
    - pytest tests/  # Запуск тестов
  only:
    - main  # Запускать только при пуше в main (измените при необходимости)