image: python:3.9

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8

test:
  stage: test
  script:
    - flake8 src/ tests/  # Проверка кода на стиль
    - pytest tests/ 
  only:
    - main
